name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pnpm:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        script: [lint]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          node-version-file: ".nvmrc"
      - run: pnpm install --frozen-lockfile
      - name: Check formatting
        run: prettier --check .
